name: "NPM Publish"
description: "NPM Publish"
inputs:
  name:
    description: "Package name"
    required: false
  version:
    description: "Package version"
    required: false
  tarball:
    description: "Tarball path"
    required: true
runs:
  using: "node20"
  main: "dist/index.js"
