name: NPM Publish
on:
  workflow_dispatch:
    inputs:
      publish-version:
        description: 'Package version'
        required: false
        type: string
      publish-name:
        description: 'Package name'
        required: false
        type: string
        default: "@109cafe/play-npm-publish"

jobs:
  build:
    uses: xc2/ghwf/.github/workflows/pnpm-artifact.yaml@main
    with:
      script: deploy
      artifact-path: "*.tgz"
      artifact-name: pkg

  npm-publish:
    runs-on: ubuntu-latest
    environment: npm-stable
    needs: build
    permissions:
      id-token: write
    steps:
      - uses: xc2/ghwf/pnpm-artifact/restore@main
        with:
          cache-key: ${{ needs.build.outputs.cache-key }}
          cache-path: ${{ needs.build.outputs.cache-path }}
      - uses: 109cafe/action-npr@summary
        with:
          version: ${{ inputs.publish-version }}
          name: ${{ inputs.publish-name }}
          tarball: ${{ needs.build.outputs.cache-path }}
          token: ${{ secrets.NPM_TOKEN }}
          provenance: true
